---
- name: Install GitLab Runner (Debian)
  include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install GitLab Runner (Fedora)
  include_tasks: install-fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Install GitLab Runner (RedHat)
  include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: Set global options
  include_tasks: global-setup.yml

- name: Register GitLab Runner
  include_tasks: register-runner.yml
